---
- name: Prepare 
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Download Chrome
      get_url: >
        url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" 
        dest=/home/{{ ansible_env.USER }}

    - name: Install Chrome
      apt: deb=/home/{{ ansible_env.USER }}/google-chrome-stable_current_amd64.deb"      

    - name: Delete Chrome file
      file: >
        path="/home/{{ ansible_env.USER }}/google-chrome-stable_current_amd64.deb"
        state=absent

