---
- name: Prepare 
  hosts: locals
  gather_facts: yes
  roles: 
    - { role: chrome, tags: chrome }  
  tasks:
    - name: Upgrade dist
      apt: upgrade=dist update_cache=yes
      sudo: yes

    - name: Install packages
      apt: >
        name={{ item }} 
        state=latest
      with_items: 
      - terminator
      - vim
      - git
      - vagrant
      - ruby
      sudo: yes

    - name: Uninstall packages 
      apt: >
        name={{ item }}
        state=absent
      with_items:
      - cowsay
      sudo: yes
