---
- name: preconfiguration
  apt: name=software-properties-common state=present
  sudo: yes

- name: Add repos
  apt_repository: repo="deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" state=present
  sudo: yes
    
- name: Upgrade dist
  apt: upgrade=dist update_cache=yes
  sudo: yes

- name: Install packages
  apt: name={{ list_of_packages_to_install | join(",") }} state=latest force=yes
  sudo: yes

- name: Uninstall packages
  apt: name={{ list_of_packages_to_uninstall | join(",") }} state=absent
  sudo: yes

- name: Install Pycharm
  file: path=/home/{{ ansible_env.USER }}/PycharmProjects state=directory
