---
# vars file for install_apps
list_of_packages_to_install:
  # terminal emulator and editors
  - terminator
  - mc
  - vim
    #  - sublime-text # sublime-text not in any repository in fedora
  - ctags
  # Version control
  - git
  - tig
  - gitk
  - subversion
  # Programming & Testing Tools
  - VirtualBox-4.3
  - vagrant
  - ruby
  - ipython
    #  - ipython3
  - python-jinja2
  - python-yaml
  - python-devel
  - sshpass
  - gcc
    #  - python-jinja2-doc
  # Communication tools
  #  - skype
  - pidgin
  # Some usefull stuff
  #  - software-properties-common
  - dropbox
  # Ansible
  - ansible

list_of_packages_to_uninstall:
  - cowsay

list_of_repositories:
  - http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
