---
- name: Check Chrome installed
  shell: dpkg -s google-chrome-stable 2>/dev/null 
  ignore_errors: yes
  register: chrome_result
  
- name: Download Chrome
  get_url: >
    url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" 
    dest=/home/{{ ansible_env.USER }}
  when: chrome_result|failed

- name: Install Chrome
  apt: deb=/home/{{ ansible_env.USER }}/google-chrome-stable_current_amd64.deb
  sudo: yes
  when: chrome_result|failed

- name: Delete Chrome file
  file: >
    path="/home/{{ ansible_env.USER }}/google-chrome-stable_current_amd64.deb"
    state=absent
  when: chrome_result|failed
